services:
  discord-bot:
    build: .
    container_name: discord_bot
    restart: always
    network_mode: host
    environment:
      - PYTHONUNBUFFERED=1
      - SSH_USER=${SSH_USER}
      - LAB_IP=${LAB_IP}
    env_file:
      - .env
    volumes:
      - .:/app
      - /home/cybercat/.ssh:/mnt/.ssh:ro
      - /var/run/docker.sock:/var/run/docker.sock
    pid: "host"